# Generated by Django 5.1.2 on 2024-11-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('vencimento', models.DateField()),
                ('setor_armazenamento', models.CharField(max_length=100)),
                ('codigo_barra', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
