# Generated by Django 4.2.16 on 2024-11-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_categoria_fornecedor_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
